### ISSUE TITLE
training does not proceed post dataset initialization

### ISSUE THREAD

**Issue by amajee11us** [YoungXIAO13/FewShotDetection#15]
Thanks for your amazing paper. But looks like the training process gets stuck after the dataset initialization stage.
Post this step specifically:
Loaded dataset `voc_2007_train_first_split` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
wrote gt roidb to /home/anay/amajee/fsod_additional_features/data/cache/voc_2007_train_first_split_gt_roidb.pkl
done
Preparing training data...
done
Loaded dataset `voc_2012_train_first_split` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
wrote gt roidb to /home/anay/amajee/fsod_additional_features/data/cache/voc_2012_train_first_split_gt_roidb.pkl
done
Preparing training data...
done
before filtering, there are 12330 images...
after filtering, there are 12330 images...

 before class filtering, there are 12330 images...
after class filtering, there are 12330 images...

12330 roidb entries
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
!!!! POST THIS there is no output for quite a long time

I am using the same environment as the repository with pytorch=0.4.0 and CUDA 8.0. Please advise on the same.

**Comment by YoungXIAO13** [comment]
Hi @amajee11us 

It seems to me the problem comes from the pertained_model weights loading. Could you verify the model resnet101 is well downloaded?  Otherwise you can get it from [here](https://www.dropbox.com/s/iev3tkbz5wyyuz9/resnet101_caffe.pth?dl=0)

**Comment by amajee11us** [comment]
Verified and closed. Thank you. Also, just to add, there seems to be a hard requirement on python 3.6+ for this codebase :)
