### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by atiszabo** [YoungXIAO13/FewShotDetection#17]
@YoungXIAO13 Do we need to have exactly the versions from the following list? 

- CUDA 8.0
- Python=3.6
- PyTorch=0.4.0
- torchvision=0.2.1
- gcc >= 4.9

I am using:

- CUDA 10.0
- Python=3.6
- PyTorch=1.5.1
- torchvision=0.6.1
- gcc = 7.5

**Comment by YoungXIAO13** [comment]
Hi @atiszabo 

As this repo is built upon the [Meta R-CNN](https://github.com/yanxp/MetaR-CNN), a further discussion on the requirement can be found in [Issue#41](https://github.com/yanxp/MetaR-CNN/issues/41) and [Issue#52](https://github.com/yanxp/MetaR-CNN/issues/52).

Apparently someone has already tried on different CUDA versions, yet not sure which version could work. My suggestion is to following the instruction proposed in these issue discussions or try to compile on your own to see if it works.

As there is no this config in my side, I could unfortunately not help much in debugging this or updating the env.
