### ISSUE TITLE
3 times few-shot training instances?

### ISSUE THREAD

**Issue by Lppy** [YoungXIAO13/FewShotDetection#23]
In meta dataset for VOC:
https://github.com/YoungXIAO13/FewShotDetection/blob/master/lib/datasets/metadata.py#L39
and for COCO:
https://github.com/YoungXIAO13/FewShotDetection/blob/master/lib/datasets/metadata_coco.py#L43

Variable **shots** are multiplied by 3:
```
if phase == 2:
    self.shots = shots * 3
```
where **shots** is the parameter passed by the command for training and is 10 or 30 for COCO:
https://github.com/YoungXIAO13/FewShotDetection/blob/master/run/finetune_coco.sh#L6

and the variable **self.shots** are used as the number of instances for each class in function **get_prndata**:
https://github.com/YoungXIAO13/FewShotDetection/blob/master/lib/datasets/metadata_coco.py#L234

Thus, in phase 2, you have 3 times instances compared with FSRW & TFA. Did I get it wrong？

**Comment by YoungXIAO13** [comment]
Hi @Lppy 

You can refer to [issue#18](https://github.com/YoungXIAO13/FewShotDetection/issues/18) and [issue#4](https://github.com/YoungXIAO13/FewShotDetection/issues/4), which pose a similar question.

**Comment by Lppy** [comment]
OK. Thanks for your reply.
