### ISSUE TITLE
Question about experimental result

### ISSUE THREAD

**Issue by geonuk-kimmm** [YoungXIAO13/FewShotDetection#3]
Thanks for a nice paper!
I have two question.

1. In a paper, you mentioned 'Results averaged over multiple random runs'.
    I'd like to ask you which of sample do you used to calculate the 'averaged results'

2. Is there experimental result with a same sample that is used by [MetaYOLO(ICCV2019)  ](https://github.com/bingykang/Fewshot_Detection/tree/master/data/vocsplit)

**Comment by YoungXIAO13** [comment]
Hi,

The results in this paper are obtained by running experiments with randomly selected support images for each experiment.
The support images used in few-shot fine-tuning stage are generated [here](https://github.com/YoungXIAO13/FewShotDetection/blob/dc329a114f4aebe00390b511d023b0208924c839/lib/datasets/metadata.py#L75) and there are filtered [here](https://github.com/YoungXIAO13/FewShotDetection/blob/dc329a114f4aebe00390b511d023b0208924c839/train.py#L274) to make sure there are only K annotated objects for each novel class.

Briefly, we run the few-shot fine-tuning stage for 10 times with different support images and then average the results over these experimental runs (similar to what has been done in a recent ICML paper [TFA](https://github.com/ucbdrive/few-shot-object-detection)).
Thus we do not use the same sample as MetaYOLO their results are only based on a single experimental run.

**Comment by Aminpdi** [comment]
Hi,

I noticed that the reported result for ICML paper(TFA) in your article is so different than what they reported.  It seems that reported results in both articles were calculated based on getting average in multiple runs in fine tuning stage.

Could you please explain how you produce the result for TFA?

Best

**Comment by YoungXIAO13** [comment]
> Hi,
> 
> I noticed that the reported result for ICML paper(TFA) in your article is so different than what they reported. It seems that reported results in both articles were calculated based on getting average in multiple runs in fine tuning stage.
> 
> Could you please explain how you produce the result for TFA?
> 
> Best

Hi,

I actually report the same results as TFA (cf. Table 7 and Table 8 in their paper). The results in Table 1 of TFA are **NOT** calculated on averaging multiple runs, they simply follow the paper FSRW to use a fixed support set.
For TFA's results on multiple runs, you can refer to the Section 4.2 (Generalized few-shot object detection benchmark) for more details.
