### ISSUE TITLE
conda create failed

### ISSUE THREAD

**Issue by Palushok** [YoungXIAO13/FewShotDetection#5]
Hello. 
An error pops up during the installation of the environment:

`CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/cudnn-6.0.21-cuda8.0_0.tar.bz2>
Elapsed: 00:00.271930
CF-RAY: 5c543dfaba149ab6-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/backports.weakref-1.0rc1-py36_0.tar.bz2>
Elapsed: 00:00.198275
CF-RAY: 5c543fb34d171ea5-AMS

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/html5lib-0.9999999-py36_0.tar.bz2>
Elapsed: 00:00.270236
CF-RAY: 5c543fc4fe45c83f-AMS

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/bleach-1.5.0-py36_0.tar.bz2>
Elapsed: 00:00.325310
CF-RAY: 5c543fd2bad4178a-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/tensorflow-gpu-base-1.3.0-py36cuda8.0cudnn6.0_1.tar.bz2>
Elapsed: 00:00.206814
CF-RAY: 5c5440460ab8bdaf-AMS

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/tensorflow-gpu-1.3.0-0.tar.bz2>
Elapsed: 00:00.404021
CF-RAY: 5c5440487e160625-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.`

Where can I find the required versions of the libraries?

Thank you

**Comment by U-Help** [comment]
I have also met this issue, have you solved this problem?

**Comment by Palushok** [comment]
> I have also met this issue, have you solved this problem?

unfortunately no

**Comment by YoungXIAO13** [comment]
Hi,
This installation file works fine on my machine (**CUDA 8.0 + python 3.6.9**).
If you encounter some broken links when creating the conda env, it would be better to first create the env and then install the necessary python packages one by one. The most important is to install the **PyTorch 0.4.0** compiled with **cuda 8.0** in order to successfully compile the dependencies:
```conda install pytorch==0.4.0 torchvision==0.2.1 cuda80 -c pytorch```
