### ISSUE TITLE
coco training time

### ISSUE THREAD

**Issue by hzhupku** [YoungXIAO13/FewShotDetection#6]
hi, i use your script run/train_coco.sh to perform base training on coco dataset. But the epoch is set to be 21, batch_size as 4, which makes training time very large, since coco is a large dataset.  I am wondering about this setting.

**Comment by YoungXIAO13** [comment]
Yes, it indeed makes the training much longer. I didn't try sth specific on tuning the learning scheduel on different datasets. But I don't think keeping the longer training time should be a big issue as there are much richer training samples in coco, thus require more optimization iterations to achieve a good perf.

**Comment by hzhupku** [comment]
May I ask about your training time on coco? Since it cost me almost two weeks to finish the training(1 TITANXP).

**Comment by YoungXIAO13** [comment]
It alos took me ~10 days to finish the whole training on COCO with one TitanX-Pascal, which is indeed very long.
As I don't have many GPUs available in hands, I did not try parallelize it with multiple GPUs, but it should be ~K times faster if you have K GPUs.
For other recently published code on few-shot object detection, you can look at [TFA](https://github.com/ucbdrive/few-shot-object-detection) and [MPSR](https://github.com/jiaxi-wu/MPSR) to get a more efficient implementations.
