### ISSUE TITLE
If possible, would you please provide the coco pre-trained weights (after base classes training)? 

### ISSUE THREAD

**Issue by pppplin** [YoungXIAO13/FewShotDetection#7]
as titled, thanks in advance!

**Comment by YoungXIAO13** [comment]
Hi,
You can get it by running the cmd ``bash download_models.sh``, which would download the pre-trained model weights for coco and pascal voc.

**Comment by pppplin** [comment]
thanks for providing the pre-trained model! 
While running download_models.sh I find 

--2020-09-21 02:21:16--  https://uc876c05c27e6ed81d264c7757b7.dl.dropboxusercontent.com/cd/0/get/A8Fn_TfDvAq_kF5_reg0Do_77AuvnBcSPqRArDOX8MA6_flwb8NxJkk9tlA2BLF-SvidENHUZCICRX5oTYQQqpzrf8s2YR_gvh7fEanTQBXxCz46Db1hCb0jULkLgxZTyWc/file
Resolving uc876c05c27e6ed81d264c7757b7.dl.dropboxusercontent.com... 162.125.3.15, 2620:100 :6018:15::a27d:30f
Connecting to uc876c05c27e6ed81d264c7757b7.dl.dropboxusercontent.com|162.125.3.15|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-21 02:21:16 ERROR 404: Not Found.

Any idea on what might happened?

**Comment by YoungXIAO13** [comment]
Hi, 
I just updated the cmd file **download_models.sh**, could you please try re-run it and see if the downloading works ?

**Comment by pppplin** [comment]
works now, thanks!
